app:
  production: false
  request-log-enabled: true
grpc-server:
  port: 9090
  timeout: 0
public-server:
  port: 8080
  timeout: 2
private-server:
  port: 8081
  timeout: 0
metrics-server:
  port: 2112
  timeout: 0
kafka:
  verbose: false
  client-name: backend-example
  brokers:
    - localhost:9094
  consumers:
    - name: test-consumer-name
      consumer-group: test-consumer
      topics:
        - test-consumer-topic
      config:
    - name: test-consumer-name1
      consumer-group: test-consumer1
      topics:
        - test-consumer-topic1
      config:
  producers:
    - name: test-producer-name
      topic: test-producer-topic
      config:

